### ISSUE TITLE
Underground reach for tier 1 surface-to-underground pipes is inconsistent (1 to small)

### ISSUE THREAD

**Issue by harag-on-steam** [TheStaplergun/pipemod#2]
![image](https://user-images.githubusercontent.com/8539331/45929013-4ae8f180-bf4c-11e8-8c59-d969df1a1119.png)

**Comment by TheStaplergun** [comment]
Fixed in commit 

https://github.com/TheStaplergun/pipemod/commit/11ce8723510c90ca86da75c87debc9ddb7924fb4

**Comment by Nexela** [comment]
Link from commit message!!!!!!
Fixes #2 in the commit message will auto close the issue :)
