### ISSUE TITLE
Placing underground connections at long range overwrite closer connections 

### ISSUE THREAD

**Issue by theunkn0wn1** [TheStaplergun/pipemod#5]
This issue occurs with Tier II and tier III undergrounds. 

The issue:
At tiers two and three, a bug exists wherein if a new underground connection is added in-line to an existing - terminated - underground connection, the old endpoint is discarded and the new endpoint is used.
Forgive me as im not sure how to word this, so i will demonstrate with pictures.

This is the reduced example, the connection off to the right leads to a water source.
![image](https://user-images.githubusercontent.com/3110986/48309942-d6d4ce00-e538-11e8-8cea-da8c368df24c.png)
In this example, we have a source of water coming in from the east, and is redirected to the south via a `Tier two underground L extension`. Once redirected, it is immediately terminated by a standard underground -to-surface pipe and, as clearly shown (and expected), the water flows into the surface pipes.

Now, lets purge the pipes add a new endpoint further down the line....
![image](https://user-images.githubusercontent.com/3110986/48309956-3206c080-e539-11e8-9208-6528ef1ee3ab.png)

The expected behavior here is for the new endpoint to be ignored, as the underground is terminated already. The other expected behavior is both endpoints are used (perhaps i missed something documentation wise? In which case both sets of pipes should be full of water.

Curiously, if we purge the pipes and mine/replace the first endpoint, the "new" endpoint is used, and the longer-range endpoint is discarded.
![image](https://user-images.githubusercontent.com/3110986/48309961-7d20d380-e539-11e8-8cb4-2f0b642fbd44.png)

Summery
--------------

The end result of this bug was grand confusion while setting up a test run for a factory design of mine in a test world. In this world i had setup a refinery to the North (see image below) that was working fine until i added certain underground connections in the newer, southern refinery. the cross-link sorted itself out after i placed a underground exit to break the link but i digress. 
![image](https://user-images.githubusercontent.com/3110986/48309988-5e6f0c80-e53a-11e8-9af5-407bfea05886.png)

Version
------------
`Advanced Underground Piping` Version `0.16.66` right off the Mods portal
Factorio version `0.16.51 (build 36654, win64, steam)`

**Comment by TheStaplergun** [comment]
Ahh, yes, you've found the way to pipe weave.
It's something to do with the game engine.
If you take a set of shorter range and a set of longer range pipes and attempt to overlap. If one long range is in connection range of the short-range, even while the short-range is connected, you can place a long range on the far side and it will "weave." It's really weird. Unfortunately this is just the game being the game and I cannot do anything about it.
