### ISSUE TITLE
Hard crash with pipe-to-ground rotation

### ISSUE THREAD

**Issue by harag-on-steam** [TheStaplergun/pipemod#6]
Just referencing the forum bug reports to help find them:

 - [Hard crash with pipe-to-ground rotation](https://forums.factorio.com/viewtopic.php?f=11&t=65824)
 - [Crash on rotate again with underground pipes](https://forums.factorio.com/viewtopic.php?f=7&t=67710)

**Comment by harag-on-steam** [comment]
Looks like [0.17.17 fixed this](https://forums.factorio.com/viewtopic.php?f=3&t=68235).

**Comment by TheStaplergun** [comment]
Fixed in https://github.com/TheStaplergun/pipemod/pull/7
