### ISSUE TITLE
Rotating of 1 to 2 perpendicular happens in opposite direction of all other pipe rotations.

### ISSUE THREAD

**Issue by credomane** [TheStaplergun/pipemod#8]
By default factorio rotates everything in clockwise direction.  
This mod rotates all pipes in clockwise direction by default.
The 1-to-2 perpendicular pipe rotates in **counter**-clockwise direction by default. This has been extremely frustrating until I figured out what was going on. Any chance this can be investigated and fixed?

**Comment by TheStaplergun** [comment]
I'm not seeing this. Could you clarify which tier it is? I believe that may have been something I fixed in https://github.com/TheStaplergun/pipemod/commit/4f375dfa45388855306da7bfd9c1ee5c790ec550

**Comment by credomane** [comment]
The tier 2 1-2 perpendicular pipes do this for certain in the 0.17.0 version of the mod.
Here is a screenshot of the rotations for ctrl+r and shift+ctrl+r for each of the pipes.  

Top is ctrl+r and rotates everything is a clockwise fashion (except the 1-2 pipes)  
Bottom is shift+ctrl+r and rotates everything is a counter clockwise fashion (except the 1-2 pipes)  

First and last pipe in each row is the starting position when first placed.
![rotations](https://user-images.githubusercontent.com/1283031/58993721-ef962100-87b3-11e9-94bd-361a40fbb4f3.png)

If you pretend the arrows on the 1-2 pipes are clock hands it is much easier to see the incorrect rotations.

**Comment by TheStaplergun** [comment]
Fixed in e7bfc1d144bfa46c1a342f378bd58291ab3a3866

**Comment by alexbarrett** [comment]
The rotation was fixed in https://github.com/TheStaplergun/pipemod/commit/e7bfc1d144bfa46c1a342f378bd58291ab3a3866 but reverted in the next commit https://github.com/TheStaplergun/pipemod/commit/9bd2263e7f0ac337db886ae2b7d247392b99cd5c. Unfortunately the change never made it to release and this issue is still a bug today.
